/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasComponentRenderer: typeof import('./components/editor/CanvasComponentRenderer.vue')['default']
    CircleShape: typeof import('./components/custom/CircleShape.vue')['default']
    DataFetcher: typeof import('./components/DataFetcher.vue')['default']
    Editor: typeof import('./components/editor/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementDemo: typeof import('./components/ElementDemo.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconHollowCircle: typeof import('./components/icons/IconHollowCircle.vue')['default']
    IconHollowRectangle: typeof import('./components/icons/IconHollowRectangle.vue')['default']
    IconHollowTriangle: typeof import('./components/icons/IconHollowTriangle.vue')['default']
    IconLetterT: typeof import('./components/icons/IconLetterT.vue')['default']
    LayerPanel: typeof import('./components/editor/LayerPanel.vue')['default']
    LineShape: typeof import('./components/custom/LineShape.vue')['default']
    Paintbrush: typeof import('./components/custom/Paintbrush.vue')['default']
    Picture: typeof import('./components/custom/Picture.vue')['default']
    PropsEditor: typeof import('./components/editor/PropsEditor.vue')['default']
    RectShape: typeof import('./components/custom/RectShape.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SVGStar: typeof import('./components/custom/SVGStar.vue')['default']
    SVGTriangle: typeof import('./components/custom/SVGTriangle.vue')['default']
    VButton: typeof import('./components/custom/VButton.vue')['default']
    VChart: typeof import('./components/custom/VChart.vue')['default']
    VTable: typeof import('./components/custom/VTable.vue')['default']
    VTag: typeof import('./components/custom/VTag.vue')['default']
    VText: typeof import('./components/custom/VText.vue')['default']
  }
}
