/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasComponentRenderer: typeof import('./components/editor/CanvasComponentRenderer.vue')['default']
    CircleShape: typeof import('./components/custom/CircleShape.vue')['default']
    DataFetcher: typeof import('./components/DataFetcher.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElementDemo: typeof import('./components/ElementDemo.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LayerPanel: typeof import('./components/editor/LayerPanel.vue')['default']
    LineShape: typeof import('./components/custom/LineShape.vue')['default']
    Picture: typeof import('./components/custom/Picture.vue')['default']
    PictureComponent: typeof import('./components/custom/PictureComponent.vue')['default']
    PropsEditor: typeof import('./components/editor/PropsEditor.vue')['default']
    RectShape: typeof import('./components/custom/RectShape.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarShape: typeof import('./components/custom/StarShape.vue')['default']
    SVGStar: typeof import('./components/custom/SVGStar.vue')['default']
    SVGTriangle: typeof import('./components/custom/SVGTriangle.vue')['default']
    TriangleShape: typeof import('./components/custom/TriangleShape.vue')['default']
    VButton: typeof import('./components/custom/VButton.vue')['default']
    VChart: typeof import('./components/custom/VChart.vue')['default']
    VTable: typeof import('./components/custom/VTable.vue')['default']
    VText: typeof import('./components/custom/VText.vue')['default']
  }
}
